import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useWallet } from '@/contexts/WalletContext';
import { Send, Bot, User, Lock, Sparkles } from 'lucide-react';

interface Message {
  id: string;
  type: 'user' | 'oracle' | 'system';
  username: string;
  content: string;
  timestamp: Date;
}

// Demo messages
const demoMessages: Message[] = [
  {
    id: '1',
    type: 'user',
    username: 'CryptoHippo',
    content: 'Hey everyone! Just joined the community 🦛',
    timestamp: new Date(Date.now() - 300000),
  },
  {
    id: '2',
    type: 'user',
    username: 'DevMaster',
    content: 'Welcome! Check out the Oracle for any dev questions.',
    timestamp: new Date(Date.now() - 240000),
  },
  {
    id: '3',
    type: 'oracle',
    username: 'OHL Oracle',
    content: 'Hello! I\'m the OHL Oracle. Ask me anything about Web3 development, smart contracts, or the OverProtocol ecosystem!',
    timestamp: new Date(Date.now() - 180000),
  },
  {
    id: '4',
    type: 'user',
    username: 'Web3Builder',
    content: 'Oracle, how do I implement ERC-721 metadata?',
    timestamp: new Date(Date.now() - 120000),
  },
  {
    id: '5',
    type: 'oracle',
    username: 'OHL Oracle',
    content: 'For ERC-721 metadata, implement the tokenURI() function that returns a URL pointing to a JSON file with name, description, and image fields. Store metadata on IPFS for decentralization.',
    timestamp: new Date(Date.now() - 60000),
  },
];

export function ChatSection() {
  const { isConnected, username, hasBasicAccess } = useWallet();
  const [messages, setMessages] = useState<Message[]>(demoMessages);
  const [newMessage, setNewMessage] = useState('');
  const [isOracleMode, setIsOracleMode] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSendMessage = () => {
    if (!newMessage.trim() || !isConnected) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      type: 'user',
      username: username || 'Anon',
      content: newMessage,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);

    // Simulate Oracle response if in Oracle mode and has access
    if (isOracleMode && hasBasicAccess) {
      setTimeout(() => {
        const oracleResponse: Message = {
          id: (Date.now() + 1).toString(),
          type: 'oracle',
          username: 'OHL Oracle',
          content: 'Thank you for your question! In a production environment, this response would be generated by GPT-4 based on your query. Enable Lovable Cloud to connect the backend!',
          timestamp: new Date(),
        };
        setMessages(prev => [...prev, oracleResponse]);
      }, 1500);
    }

    setNewMessage('');
  };

  const formatTime = (date: Date) => {
    return date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <section id="chat" className="py-24 relative">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <span className="inline-block px-4 py-2 glass-card rounded-full text-sm text-primary mb-4">
            Live Preview
          </span>
          <h2 className="font-display text-4xl md:text-5xl font-bold mb-4">
            <span className="text-foreground">Overworld</span>{' '}
            <span className="text-primary neon-text">Chat</span>
          </h2>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-4xl mx-auto"
        >
          <div className="glass-card rounded-2xl overflow-hidden">
            {/* Chat Header */}
            <div className="flex items-center justify-between p-4 border-b border-border">
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 bg-neon-green rounded-full animate-pulse" />
                <span className="font-display text-lg font-semibold">Overworld Chat</span>
                <span className="text-xs text-muted-foreground">({messages.length} messages)</span>
              </div>
              
              <div className="flex items-center gap-2">
                <Button
                  variant={isOracleMode ? 'cyber' : 'outline'}
                  size="sm"
                  onClick={() => setIsOracleMode(!isOracleMode)}
                  disabled={!hasBasicAccess}
                >
                  <Bot className="w-4 h-4" />
                  Oracle Mode
                  {!hasBasicAccess && <Lock className="w-3 h-3 ml-1" />}
                </Button>
              </div>
            </div>

            {/* Messages */}
            <div className="h-96 overflow-y-auto p-4 space-y-4">
              <AnimatePresence>
                {messages.map((message) => (
                  <motion.div
                    key={message.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                    className={`flex items-start gap-3 ${
                      message.type === 'oracle' ? 'bg-secondary/30 p-3 rounded-xl' : ''
                    }`}
                  >
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
                      message.type === 'oracle' 
                        ? 'bg-oracle-gradient' 
                        : 'bg-primary/20'
                    }`}>
                      {message.type === 'oracle' ? (
                        <Sparkles className="w-4 h-4 text-foreground" />
                      ) : (
                        <User className="w-4 h-4 text-primary" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className={`font-semibold text-sm ${
                          message.type === 'oracle' ? 'text-accent' : 'text-primary'
                        }`}>
                          {message.username}
                        </span>
                        <span className="text-xs text-muted-foreground">
                          {formatTime(message.timestamp)}
                        </span>
                      </div>
                      <p className="text-sm text-foreground break-words">{message.content}</p>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
              <div ref={messagesEndRef} />
            </div>

            {/* Input */}
            <div className="p-4 border-t border-border">
              {isConnected ? (
                <div className="flex gap-3">
                  <Input
                    value={newMessage}
                    onChange={(e) => setNewMessage(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                    placeholder={isOracleMode ? "Ask the Oracle a question..." : "Type your message..."}
                    className="flex-1 bg-input border-border"
                  />
                  <Button variant="cyber" onClick={handleSendMessage}>
                    <Send className="w-4 h-4" />
                  </Button>
                </div>
              ) : (
                <div className="text-center py-4">
                  <p className="text-muted-foreground mb-2">Connect your wallet to join the chat</p>
                  <Button variant="cyber">Connect Wallet</Button>
                </div>
              )}
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
